
rem delete all gif, demo pic
del .\*.gif /f /s /q /a
del .\demo*.jpg /f /s /q /a
del .\demo*.png /f /s /q /a
del .\cn*.png /f /s /q /a
del .\cn*.jpg /f /s /q /a
del .\base*.jpg /f /s /q /a
del .\base*.png /f /s /q /a
del .\use*.jpg /f /s /q /a
del .\use*.png /f /s /q /a
del .\banner*.jpg /f /s /q /a
del .\banner*.png /f /s /q /a
del .\mail*.jpg /f /s /q /a
del .\mail*.png /f /s /q /a
del .\hr*.jpg /f /s /q /a
del .\hr*.png /f /s /q /a
del .\sale*.jpg /f /s /q /a
del .\sale*.png /f /s /q /a
del .\purchase*.jpg /f /s /q /a
del .\purchase*.png /f /s /q /a
del .\stock*.jpg /f /s /q /a
del .\stock*.png /f /s /q /a
del .\mrp*.jpg /f /s /q /a
del .\mrp*.png /f /s /q /a
del .\super*.jpg /f /s /q /a
del .\super*.png /f /s /q /a
del .\*.docx /f /s /q /a
del .\*.pdf /f /s /q /a
del .\*.xmind /f /s /q /a
